# Generated by Django 3.0.7 on 2020-06-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pachaqtecfarma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['product'], 'verbose_name': 'Resumen', 'verbose_name_plural': 'Resumenes'},
        ),
    ]
