# Generated by Django 3.0.7 on 2020-06-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachaqtecfarma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['product'], 'verbose_name': 'Resumen', 'verbose_name_plural': 'Resumenes'},
        ),
        migrations.AddField(
            model_name='resume',
            name='sub_total',
            field=models.FloatField(default=0),
        ),
    ]
