# Generated by Django 3.0.7 on 2020-06-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachaqtecfarma', '0002_auto_20200627_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
